### ISSUE TITLE
How to deal with negative values?

### ISSUE THREAD

**Issue by Doraemonzzz** [sail-sg/Attention-Sink#1]
Thank you for your very insightful work. I would like to ask how you handle the negative values in the sim(Q, K) matrix when computing $\mathrm{Sink}_k^\epsilon$. For example, in Table 6, the expression $\frac{{q}_i {k}_j^T}{\sqrt{d_h}}$ may produce negative numbers.

**Comment by guxm2021** [comment]
Thank you for your question, when computing $\textrm{Sink}_k^{\epsilon}$, for negative attention, we use $\textrm{abs}(sim(Q_i, K_j)) / \sum_n \textrm{abs}(sim(Q_i, K_n))$ to compute the proxy attention scores. As attention sink and massive activations always concurrently occur, we also monitor whether there are massive activations.

**Comment by Doraemonzzz** [comment]
Thank you for your reply.
